---
name: registripe_group
---
EventAttendee:
  extensions:
    - EventAttendeeGroupExtension
EventTicket:
  extensions:
    - EventTicketGroupExtension
TicketSelection:
  extensions:
    - RegistrationGroupTicketSelectionExtension

EventRegisterController:
  extensions:
    - EventRegisterControllerGroupExtension
    
RegistrationGroupController:
  ticket_select_template: TicketCountSelections

RegistrationGroupEventTicket:
  selection_type: RegistrationGroupTicketSelection
