---
name: registripe_group
---
EventAttendee:
  extensions:
    - EventAttendeeGroupExtension

TicketSelection:
  extensions:
    - RegistrationGroupTicketSelectionExtension

RegistrationGroupTicketSelection:
  calculators:
    - GroupTicketSelection

EventRegisterController:
  extensions:
    - EventRegisterControllerGroupExtension
    
RegistrationGroupController:
  ticket_select_template: TicketCountSelections

RegistrationGroupEventTicket:
  selection_type: RegistrationGroupTicketSelection
